run "ln -s /data/#{config.app}/shared/log #{config.current_path}/logs"
run "chmod -R 777 /data/#{config.app}/shared/log"
run "mkdir #{config.shared_path}/uploads"
run "chmod -R 777 #{config.shared_path}/uploads"
run "ln -s /data/#{config.app}/shared/uploads #{config.current_path}/uploads"
